# Generated by Django 4.2.6 on 2023-10-28 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('agency', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=125)),
                ('purposeOfVisit', models.CharField(max_length=125)),
                ('dateOfVisit', models.DateField()),
                ('department', models.CharField(blank=True, max_length=40, null=True)),
                ('staff', models.CharField(blank=True, max_length=40, null=True)),
                ('courtesy', models.PositiveIntegerField()),
                ('quality', models.PositiveIntegerField()),
                ('timeless', models.PositiveIntegerField()),
                ('efficiency', models.PositiveIntegerField()),
                ('cleanliness', models.PositiveIntegerField()),
                ('comfort', models.PositiveIntegerField()),
                ('comment', models.TextField(max_length=255)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'visithoughtsform_feedback',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visithoughtsForm.department')),
            ],
        ),
    ]
