# Generated by Django 4.2.6 on 2023-12-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visithoughtsForm', '0002_alter_feedback_comment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='department',
            table='visithoughtsform_department',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='visithoughtsform_staff',
        ),
    ]
